name: Netlify Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: nazariifenii/e-commerce-system:${{ github.sha }}

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: .
        deploy-dir: /usr/share/nginx/html
        publish-command: |
          docker pull nazariifenii/e-commerce-system:${{ github.sha }}
          docker run -d --name e-commerce-system -p 8080:80 nazariifenii/e-commerce-system:${{ github.sha }}
        github-token: ${{ secrets.REPO_GIT_TOKEN }}
        site-id: 165756c1-5309-453f-bf61-5ac8c1df440a
